{
 "title": "Groupe 7 — League of Legends Monitoring",
 "refresh": "1s",
 "panels": [
  {
   "title": "Joueurs connectés — EUW",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(game_players_connected_by_region{region=\"EUW\"})",
     "legendFormat": "EUW"
    }
   ]
  },
  {
   "title": "Joueurs connectés — NA",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(game_players_connected_by_region{region=\"NA\"})",
     "legendFormat": "NA"
    }
   ]
  },
  {
   "title": "Joueurs connectés — KR",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(game_players_connected_by_region{region=\"KR\"})",
     "legendFormat": "KR"
    }
   ]
  },
  {
   "title": "KDA moyen",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_player_kda_avg{app=\"groupe7\"}",
     "legendFormat": "KDA"
    }
   ]
  },
  {
   "title": "CS/min moyen",
   "type": "gauge",
   "gridPos": { "x": 16, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_player_cs_per_min_avg{app=\"groupe7\"}",
     "legendFormat": "CS/min"
    }
   ]
  },
  {
   "title": "Alertes ouvertes",
   "type": "stat",
   "gridPos": { "x": 20, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_alerts_open{app=\"groupe7\"}",
     "legendFormat": "Alertes"
    }
   ]
  },
  {
   "title": "Joueurs connectés par région — historique",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "game_players_connected_by_region{region=\"EUW\"}",
     "legendFormat": "EUW"
    },
    {
     "expr": "game_players_connected_by_region{region=\"NA\"}",
     "legendFormat": "NA"
    },
    {
     "expr": "game_players_connected_by_region{region=\"KR\"}",
     "legendFormat": "KR"
    }
   ]
  },
  {
   "title": "Matchs en cours par mode",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "game_matches_active_by_mode{mode=\"RANKED_SOLO\"}",
     "legendFormat": "Ranked Solo"
    },
    {
     "expr": "game_matches_active_by_mode{mode=\"RANKED_FLEX\"}",
     "legendFormat": "Ranked Flex"
    },
    {
     "expr": "game_matches_active_by_mode{mode=\"NORMAL_DRAFT\"}",
     "legendFormat": "Normal Draft"
    },
    {
     "expr": "game_matches_active_by_mode{mode=\"ARAM\"}",
     "legendFormat": "ARAM"
    }
   ]
  },
  {
   "title": "Top champions joués",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8, game_champion_players{app=\"groupe7\"})",
     "legendFormat": "{{champion}}"
    }
   ]
  },
  {
   "title": "Distribution des tiers",
   "type": "bargauge",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_players_by_tier{tier=\"IRON\"}",
     "legendFormat": "Iron"
    },
    {
     "expr": "game_players_by_tier{tier=\"BRONZE\"}",
     "legendFormat": "Bronze"
    },
    {
     "expr": "game_players_by_tier{tier=\"SILVER\"}",
     "legendFormat": "Silver"
    },
    {
     "expr": "game_players_by_tier{tier=\"GOLD\"}",
     "legendFormat": "Gold"
    },
    {
     "expr": "game_players_by_tier{tier=\"PLATINUM\"}",
     "legendFormat": "Platinum"
    },
    {
     "expr": "game_players_by_tier{tier=\"DIAMOND\"}",
     "legendFormat": "Diamond"
    },
    {
     "expr": "game_players_by_tier{tier=\"MASTER\"}",
     "legendFormat": "Master"
    },
    {
     "expr": "game_players_by_tier{tier=\"CHALLENGER\"}",
     "legendFormat": "Challenger"
    }
   ]
  },
  {
   "title": "KDA moyen — historique",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 20, "w": 8, "h": 7 },
   "targets": [
    {
     "expr": "game_player_kda_avg{app=\"groupe7\"}",
     "legendFormat": "KDA moyen"
    }
   ]
  },
  {
   "title": "CS/min moyen — historique",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 20, "w": 8, "h": 7 },
   "targets": [
    {
     "expr": "game_player_cs_per_min_avg{app=\"groupe7\"}",
     "legendFormat": "CS/min"
    }
   ]
  },
  {
   "title": "Charge serveurs",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 20, "w": 8, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "game_server_load_avg{app=\"groupe7\"} * 100",
     "legendFormat": "Charge %"
    }
   ]
  },
  {
   "title": "Requêtes HTTP/s",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 27, "w": 12, "h": 7 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"groupe7-monitoring\"}[30s])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 27, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"groupe7-monitoring\", area=\"heap\"}",
     "legendFormat": "Heap utilisé"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"groupe7-monitoring\",  area=\"heap\"}",
     "legendFormat": "Heap max"
    }
   ]
  },
  {
   "title": "Matchs termines (Kafka) — cumul",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 34, "w": 6, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_match_finished_total{app=\"groupe7\"}",
     "legendFormat": "total"
    },
    {
     "expr": "rate(kafka_match_finished_total{app=\"groupe7\"}[30s])*60",
     "legendFormat": "par min"
    }
   ]
  },
  {
   "title": "Bans joueurs (Kafka) — cumul",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 34, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "kafka_player_banned_total{app=\"groupe7\"}",
     "legendFormat": "total bans"
    },
    {
     "expr": "rate(kafka_player_banned_total{app=\"groupe7\"}[30s])*60",
     "legendFormat": "par min"
    }
   ]
  },
  {
   "title": "MAJ ELO (Kafka) — cumul",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 34, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "kafka_score_updated_total{app=\"groupe7\"}",
     "legendFormat": "total"
    },
    {
     "expr": "rate(kafka_score_updated_total{app=\"groupe7\"}[30s])*60",
     "legendFormat": "par min"
    }
   ]
  },
  {
   "title": "Serveurs surcharges (Kafka) — cumul",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 34, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "kafka_server_overloaded_total{app=\"groupe7\"}",
     "legendFormat": "total"
    },
    {
     "expr": "rate(kafka_server_overloaded_total{app=\"groupe7\"}[30s])*60",
     "legendFormat": "par min"
    }
   ]
  }
 ]
}